-- INSERT ON key
INSERT INTO key VALUES(DEFAULT, 0);
INSERT INTO key VALUES(DEFAULT, 10);
INSERT INTO key VALUES(DEFAULT, 1);

-- INSERT ON USER
INSERT INTO product VALUES(DEFAULT, 0.5, 50, 'Coffee');
INSERT INTO product VALUES(DEFAULT, 0.8, 10, 'The');
INSERT INTO product VALUES(DEFAULT, 1.2, 30, 'Milk');
INSERT INTO product VALUES(DEFAULT, 1.2, 10, 'Chamomile');
INSERT INTO product VALUES(DEFAULT, 1.2, 20, 'Hot Chocolate');
INSERT INTO product VALUES(DEFAULT, 1.2, 30, 'Hot Water');
